### ISSUE TITLE
Request: AmazonSQSConfigurationExtensions.UseAmazonSQSAsOneWayClient method signature that accepts an AWSCredentials object

### ISSUE THREAD

**Issue by jonathanyong81** [rebus-org/Rebus.AmazonSQS#12]
Hi,

Would it be possible to add a version of the UseAmazonSQSAsOneWayClient extension method to accept an AWSCredentials object?

This would allow us to create an InstanceProfileAWSCredentials object (our app is running in an EC2 instance) instead of having to supply the accessKey and secretKey.

Thanks.

**Comment by mookid8000** [comment]
Yes, definitely :)

**Comment by jonathanyong81** [comment]
Thanks! Actually why don't I just make the change and submit a pull request. It's a tiny change. I just need to integrate Visual Studio with Github and learn the fork / pull request process.

**Comment by mookid8000** [comment]
that would be quite awesome 😄  I can see you already created the fork – I believe you are well on your way. Let me know if there's something you need

**Comment by jonathanyong81** [comment]
Resolved via #13
