### ISSUE TITLE
support for SNS and Kinesis

### ISSUE THREAD

**Issue by drewburlingame** [rebus-org/Rebus.AmazonSQS#2]
We're about to implement SNS subscription store and transport and soon after, we'll add support for Kinesis streams.  I'm curious if you've looked into these and have any gotcha's you'd like to share.

Our plan is to create 

- Rebus.AmazonSNS repo with a package containing
  - SnsTransport: publish only
  - SnsSubscriptionStore
  - SnsSqsTransport: uses the SnsTransport for publish & this SqsTransport for receive

- Rebus.AmazonKinesis repo with a package containing
  - KinesisTransport: publish and receive.  will implement KCL's IRecordProcessor to feed messages from KCL into the rebus pipeline.
  - (considering) update to SnsSubscriptionStore or new SnsKinesisTransport to create a lambda that will forward from SNS to a Kinesis stream.

Does that sound reasonable?  Do you have any recommendations or requests?

**Comment by mookid8000** [comment]
It sounds awesome 😁 👏   I don't know anything about SNS and Kinesis though, so I have no idea whether it makes sense to do what you are talking about 😬 

Maybe you can enlighten me by telling me what this adds, compared to the existing AmazonSQS transport?

**Comment by drewburlingame** [comment]
## SQS:
this post does a good job explaining SNS vs SQS. http://stackoverflow.com/questions/13681213/what-is-the-difference-between-amazon-sns-and-amazon-sqs

> SNS is a distributed publish-subscribe system. Messages are pushed to subscribers as and when they are sent by publishers to SNS. SQS is distributed queuing system. Messages are NOT pushed to receivers.

![image of SNS feeding SQS](http://docs.aws.amazon.com/sns/latest/dg/images/sns-fanout.png)

SNS can also forward to email, sms, mobile, lambda and http endpoints. http://docs.aws.amazon.com/sns/latest/dg/SNS_Scenarios.html

in rebus terms, SNS can serve as an ISubscriptionStore

## Kinesis:
This post does a great job of explaining Kinesis.  https://aws.amazon.com/kinesis/streams/faqs/ 
  
My short answer... Kinesis is Amazon's version of Kafka.  It's a type of message transport with different delivery guarantees like guaranteed order & the ability to reprocess events.

**Comment by mookid8000** [comment]
Is it correctly understood then, that SNS is used as a pub/sub mechanism that can be used to broadcast messages, but the messages still end up in good old SQS queues?

Because in that case it would be a brilliant addition to either

1. Create a new transport that uses SQS and SNS combined, similar to how the Azure Service Bus transport does it, or
1. Augment the existing SQS transport to insert a `ISubscriptionStorage` implementation and then make the transport use SNS when publishing messages

Does SNS have the same delivery guarantees as ordinary queues? As in: When a message is successfully published, can you then count on it being delivered to each queue that was subscribed at that time?


Regarding Kinesis – I have before discussed creating a Kafka transport for Rebus, but it has never been clear to me exactly how one could use Kafka as a queue..... in my head it is more an event store type of database, storing streams and stuff like that – but maybe it's just a problem with my imagination? 😬

**Comment by drewburlingame** [comment]
>**Q: Does Amazon SNS provide at-least-once message delivery to Amazon SQS queues?**
Yes. Amazon SNS guarantees that each message is delivered to Amazon SQS at least once.
For non-SQS endpoints, see "Does Amazon SNS guarantee that messages are delivered to the subscribed endpoint?"

>**Q: Does Amazon SNS guarantee that messages are delivered to the subscribed endpoint?**
When a message is published to a topic, Amazon SNS will attempt to deliver notifications to all subscribers registered for that topic. Due to potential Internet issues or Email delivery restrictions, sometimes the notification may not successfully reach an HTTP or Email end-point. In the case of HTTP, an SNS Delivery Policy can be used to control the retry pattern (linear, geometric, exponential backoff), maximum and minimum retry delays, and other parameters. If it is critical that all published messages be successfully processed, developers should have notifications delivered to an SQS queue (in addition to notifications over other transports).

**Comment by drewburlingame** [comment]
I think we should create a new AmazonSnsSqsTransport because there are use cases for using just SQS.  Would you prefer we append to this repo or create a new one?

Kinesis is an event store for streaming event.  Processing those events though is the same as processing messages, so in many ways, Kinesis is just another messaging transport, but with different delivery guarantees.

**Comment by mookid8000** [comment]
> I think we should create a new AmazonSnsSqsTransport because there are use cases for using just SQS. Would you prefer we append to this repo or create a new one?

I would prefer a new repository – would it be called something like `Amazon.SnsSqs` then, or do you have a name in mind?

**Comment by drewburlingame** [comment]
I was thinking AmazonSns, and having a dependency on this AmazonSqs repo for the Sqs transport.

**Comment by mookid8000** [comment]
Ah – so you are thinking about adding the SNS by leveraging the existing SQS transport?

**Comment by drewburlingame** [comment]
Yes, that's the current thinking.

**Comment by mookid8000** [comment]
In that case I think you should just add it to the current AmazonSQS repo

**Comment by drewburlingame** [comment]
👍

**Comment by jmfn** [comment]
@drewburlingame Can I lend a hand with the SNS support? I didn't see a fork.

**Comment by drewburlingame** [comment]
@jmfn  unfortunately, due to constraints, the team that took this on didn't implement it in a way that could be contributed back.  and i don't think we'll be able to get back to it anytime soon.
