### ISSUE TITLE
Doesn't work with .net core 2.1

### ISSUE THREAD

**Issue by replaysMike** [rebus-org/Rebus.AmazonSQS#20]
Just thought I'd drop this here after a few hours of frustrated debugging.

Running under core 2.1 gives the error when authenticating:

`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method`

Switching to core 2.0 works fine. Though, that will present a challenge for me.

**Comment by replaysMike** [comment]
This may be specific to the AWSSDK, it's certainly blowing up during the POST request to amazon. I'll drop them a note as well, I wasn't able to spot what's causing it. Could be encryption libraries in .net core, or some funky headers they are being restrictive on.

**Comment by mookid8000** [comment]
Damn! Let me know if there’s something I can do

**Comment by replaysMike** [comment]
A working solution was provided over at [AWSSDK](https://github.com/aws/aws-sdk-net/issues/932) . While I couldn't get a config-level solution to work, a code-level one did work:

calling 
`AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);` from the .net core 2.1 app does resolve the issue.
