### ISSUE TITLE
Rebus is publishing to queues it's not configured for

### ISSUE THREAD

**Issue by cjesp** [rebus-org/Rebus.AmazonSQS#21]
I'm having issues with running Rebus over Amazon SQS.

I have a service that runs on 3 different levels; test, qat, prod. I want independent queues for each level of service instance, so not to interfere with each other even though it's the same types we're sending (same Assembly). Alright, we have two services: a publisher and consumer of messages.

The publisher is configured as follows:
```
var sqsConfig = new AmazonSQSConfig() { RegionEndpoint = RegionEndpoint.USEast1 };
                var credentials = new BasicAWSCredentials(Configuration.AWSKey, Configuration.AWSSecret);
                _sqsBus = Configure.With(new BuiltinHandlerActivator())
                    .Transport(t => t.UseAmazonSQS(credentials, sqsConfig, _nameOfQueue))
                    .Routing(r => r.TypeBased().MapAssemblyOf<TemplateTestEmail>(_nameOfQueue))
                    .Subscriptions(s => s.UseJsonFile(_jsonFilePath))
                    .Start();

                return _sqsBus;
```

where _nameOfQueue is "myservice-test-publisher". I Send messages like
```
_bus.Publish(message);
```

Then I have a consumer with the following config:
```
_bus = Configure.With(_activator)
                .Transport(t => t.UseAmazonSQS(credentials, sqsConfig, _consumerQueue))
                .Routing(r => r.TypeBased().MapAssemblyOf<TemplateTestEmail>(_publisherQueue))
                .Options(o => o.SimpleRetryStrategy(_errorQueue))
                .Start();
```
where _consumerQueue is "myservice-test-consumer", _publisherQueue is "myservice-test-publisher", and _errorQueue is "myservice-test-error". Under this config everything is running fine; All published messages are consumed by the consumer. Usage is straight forward with IHandleMessages<Type> handlers and subscription like 
```
  _bus.Subscribe<Type...>().Wait();
```
And everything is running fine.

Now, lets say I shut down my publisher service and restart it with _nameOfQueue is "myservice-qat-publisher". It starts and creates the right queue, e.g. "myservice-qat-publisher", but when I publish a message it ends up being consumed by the "test" consumer on queue "myservice-test-consumer". Note it does not matter if I shut down a consumer or vice versa, no matter what every consumer ends up consumer messages from other levels (test, qat, prod).

However, I do notice that, if I start up a consumer with no publishers running, I can tell that the Subscribe requests goes to the right queues, e.g. in the test level the test consumer will send the subscribe messages with the correct header:
```
"rbs2-return-address": "https://sqs.(...)/myservice-test-consumer",
```
 to the myservice-test-publisher queue which of course will be consumed on startup of the publisher.

My question is why does this happen, and is there a way to solve it? I note that there's not support for Amazon SNS (topics), which I guess would solve my problem. I've used Rebus before with RabbitMQ without any issues. 

My setup is as follows:
- for all services there will only be one consumer
- there might be more than one publishers to a given queue.
- there are 3 levels (test, qat, prod)
- we use same aws credentials, region etc. for all levels and queus.

**Comment by mookid8000** [comment]
You should probably adapt your `_jsonFilePath` so that there is one for each environment.

When the subscriber has subscribed, the JSON file contains the subscriber's queue name until it unsubscribes, no matter if endpoints are restarted.

I suggest you make the current environment part of your application's configuration (if it isn't already) and then use it to generate a subscriptions file path on the form `subscriptions.<environment>.json`, e.g. `subscriptions.qat.json`.
