### ISSUE TITLE
v3 and v4 compatiblity

### ISSUE THREAD

**Issue by danpowell88** [rebus-org/Rebus.AmazonSQS#22]
It seems like between version 3 and 4 the way the messages were created has changed.

In v3 the entire message is base64 encoded and sent as the SQS message body and the headers are sent as message attributes and in v4 the header and body are sent in the sqs body, with only the body itself being base64 encoded.

This causes incompatiblities and forced upgrade between the versions which isn't an easy thing to do in all circumstances.

It would seem this could be worked around with a small change in the ExtractTransportMessageFrom method

``` csharp
TransportMessage ExtractTransportMessageFrom(Message message)
{
    var sqsMessage = _serializer.Deserialize(message.Body);
    return new TransportMessage(sqsMessage.Headers, GetBodyBytes(sqsMessage.Body));
 }
```

If the deserialise fails try to base64 decode the message then try the deserialisation again.

Any chance you would be able to include something like this?

**Comment by kz412** [comment]
I've managed to work around this by checking whether there are any MessageAttributes present on the SQS message in `ExtractTransportMessageFrom`, i.e.:
```csharp
TransportMessage ExtractTransportMessageFrom(Message message)
{
    if (message.MessageAttributes.Any())
    {
        return new TransportMessage(message.MessageAttributes.ToStringDictionary(), GetBodyBytes(message.Body));
    }

    var sqsMessage = _serializer.Deserialize(message.Body);
    return new TransportMessage(sqsMessage.Headers, GetBodyBytes(sqsMessage.Body));
}
```

using an extension method to unwrap MessageAttributes:
```csharp
internal static Dictionary<string, string> ToStringDictionary(this IDictionary<string, MessageAttributeValue> src)
{
   return src.Where(pair => pair.Value.DataType == "String")
       .ToDictionary(pair => pair.Key, pair => pair.Value.StringValue);
}
```

I'm not sure how robust this would be though, as it makes the assumption that there will never be MessageAttributes present for v4 messages.

**Comment by mookid8000** [comment]
@danpowell88  so.... were you able to work around this, or is this still a problam?
