### ISSUE TITLE
Support for FIFO queues

### ISSUE THREAD

**Issue by knepe** [rebus-org/Rebus.AmazonSQS#24]
Hi
When using a queue with type "FIFO" the request fails with "The request must contain the parameter MessageGroupId." I have tried to set the Header "MessageGroupId" but that does not make any difference (it is not a Header, but a Parameter). 

I think this library should support this, as the FIFO queue is a great feature in AWS.
Any thoughts?

**Comment by mookid8000** [comment]
hmm, sounds like it would be useful if Rebus' SQS transport would map a `MessageGroupId` header to the parameter on the SQS client

**Comment by knepe** [comment]
I did a PR, is this what you had in mind @mookid8000 ?

**Comment by mookid8000** [comment]
Yes, that's exactly what I had in mind 😄
