### ISSUE TITLE
Problem with deferred messages

### ISSUE THREAD

**Issue by ovd-capturi** [rebus-org/Rebus.AmazonSQS#29]
If I defer a message it appears in the senders input queue with defer headers. It never gets delivered to the destination queue.

Below the documentation from the wiki. Haven't configured anything regarding the timeout manager. 

---

Transports WITH native support for deferred messages
When the transport supports delayed delivery, the message is usually deferred simply by setting a timestamp on the message when sending it, causing it to stay invisible in its destination queue until that time comes.

This works out-of-the-box with the Azure Service Bus tranport, the Azure Storage Queues transport, and the Amazon SQS transport. Curiously, it also works with the SQL Server transport, as all messages are provided with a visible DateTime2 value, which is used by the transport when querying for messages to receive.

**Comment by mookid8000** [comment]
Found a bug 😐  has been fixed in Rebus.AmazonSqs 6.1.2, which is on NuGet.org in a few minutes.

Thanks for reporting it! 😄
