### ISSUE TITLE
Port to .NET standard

### ISSUE THREAD

**Issue by mvandevy** [rebus-org/Rebus.AmazonSQS#3]
The library isn't compatible with .NET standard yet. Just like I've (just) created a pull request that would make the Rebus main lib compatible with both .NET Standard and .NET 4.5, I'd like to port the library to be compatible with both target frameworks. How can I proceed? Would you be able to give me a branch for this? Or can I create a pull request for the master branch?

**Comment by mookid8000** [comment]
The new [4.0.0-b01](https://www.nuget.org/packages/Rebus.AmazonSQS/4.0.0-b01) targets .NETStandard1.6 🤘
