### ISSUE TITLE
Dependency package versions

### ISSUE THREAD

**Issue by RMaschkiwitz** [rebus-org/Rebus.AmazonSQS#32]
Hi! We are using this package in our software and my colleagues Dieter Mijle and Rob van Pamel already contributed here.

We are working on introducing feature flags/toggles into our project. By using AWSSDK.AppConfig package, we have added a dependency to the AWSSDK.Core package version >= 3.5.2.10.
In this project there are references to AWSSDK.SQS 3.3.103.21 and AWSSDK.SecurityToken 3.3.105.38, which both are also dependent on the AWSSDK.Core, but limited to versions <= 3.4.0, which is why we would like to update the dependencies here to use newer versions of the Core package.

**Comment by mookid8000** [comment]
Done 🙂 it's out as Rebus.AmazonSqs 6.3.0 on NuGet.org in a few minutes
