### ISSUE TITLE
deferCount is not increasing

### ISSUE THREAD

**Issue by djhvscf** [rebus-org/Rebus.AmazonSQS#34]
Hi @mookid8000 after testing your fix (refer to this [issue](https://github.com/rebus-org/Rebus.AmazonSQS/issues/33)), it is still happening, deferCount is reaching 1 and then it is doing nothing different. One thing to add is that we're using this library https://github.com/raol/amazon-sqs-net-extended-client-lib

Do you think that use the CorrelationSequence is a good workaround?

**Comment by mookid8000** [comment]
> One thing to add is that we're using this library https://github.com/raol/amazon-sqs-net-extended-client-lib

This part I don't understand - what do you mean when you say that you are using that library?

**Comment by djhvscf** [comment]
Yes, we use that library in order to support connection to S3 since some messages are bigger than 256kb (SQS limit)

**Comment by mookid8000** [comment]
Could you maybe show me your Rebus configuration code?

**Comment by djhvscf** [comment]
@mookid8000 Appreciate your help. This is fixed now since the owner of that library just published a new version.

**Comment by mookid8000** [comment]
Ok, great 🙂
