### ISSUE TITLE
A message received from SQS just after bus disposal is made invisible in SQS

### ISSUE THREAD

**Issue by xhafan** [rebus-org/Rebus.AmazonSQS#35]
When a bus is disposed, the message receiving from SQS is cancelled, but when a message it sent by SQS quickly enough before the socket is closed, the message is marked by SQS as invisible, and will be handled only after the message visibility timeout.

The scenario above seems to be similar to what NServiceBus team reported for AWS SDK: https://github.com/aws/aws-sdk-net/issues/796#issuecomment-375494537: _It looks like there's a race condition when the request gets canceled. When the CancellationSource gets triggered control returns to the calling code but the socket isn't closed yet. So even though a message is sent after the previous ReceiveMessage request has been canceled the socket from the previous receive is still open. SQS replies over the old socket with the new message, considers it received, and subjects the message to the visibility timeout._

The suggested workaround not passing `cancellationToken` into `sqsClient.ReceiveMessageAsync()` but passing in `CancellationToken.None` works for me:
![image](https://user-images.githubusercontent.com/13038902/119779487-06fed500-bec9-11eb-81e0-71d74f8a62f4.png)
The downside is that the bus disposal is not immediate with this workaround, but it takes up to 20s.

The [AWS SDK issue](https://github.com/aws/aws-sdk-net/issues/796) was closed in 2018, and @vellozi [mentioned](https://github.com/aws/aws-sdk-net/issues/796#issuecomment-375494537) _We're still looking into how the CancellationToken works within the HTTP client, and possible solutions to that._. But I don't think they've resolved it somehow, so I assume we will have to live with this workaround and the bus disposal taking up to 20s.

Original SO question: https://stackoverflow.com/questions/67656986/a-message-received-from-sqs-by-a-stopped-aws-ecs-instance-is-handled-by-rebus-on

**Comment by xhafan** [comment]
I found this: https://stackoverflow.com/a/45562557/379279 `HttpClient cancellation doesn't kill underlying TCP call`: _HttpClient re-uses connections as much as possible, hence the reason why the connection is not closed on cancel. When canceling a request like that, the HttpClient will just stop sending/receiving data to/from the other end. It will not send anything to inform the other end that it was cancelled._
So I guess that's it - the solution is to stop using cancellations with `HttpClient`, and the workaround looks like the proper solution.

**Comment by mookid8000** [comment]
Solved by #36 which is available on NuGet.org as Rebus.AmazonSQS 6.3.2
