### ISSUE TITLE
Suggestion: Add required ACL's to readme.md?

### ISSUE THREAD

**Issue by ThomasEg** [rebus-org/Rebus.AmazonSQS#37]
While setting up a service using Rebus.AmazonSQS i needed to know what permissions the service required, i had to browse the code to see which endpoints where called. Maybe it could be something to write in the readme.md under some sort of requirements paragraph?

This is the policy i've found to be working:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl",
                "sqs:ChangeMessageVisibility",
                "sqs:DeleteMessageBatch",
                "sqs:SendMessageBatch",
                "sqs:ReceiveMessage",
                "sqs:DeleteQueue",
                "sqs:CreateQueue",
                "sqs:SetQueueAttributes"
            ],
            "Resource": "[Your SQS queue arn here]"
        }
    ]
}
```
Note: If your sevice don't own the queue(aka `CreateQueue: False`) then the last 3 permissions can/should be omitted...

**Comment by mookid8000** [comment]
Great suggestion! But, I am an Amazon n00b, so if it's not too much trouble for you, could you maybe go to https://github.com/rebus-org/Rebus.AmazonSQS/blob/master/README.md and click the little pencil symbol near the top right corner? It'll fork & edit, making it super-easy for you to submit a PR....

**Comment by ThomasEg** [comment]
Sure thing! I've made PR **https://github.com/rebus-org/Rebus.AmazonSQS/pull/38**
