### ISSUE TITLE
Change visibility time on abort

### ISSUE THREAD

**Issue by kostazol** [rebus-org/Rebus.AmazonSQS#39]
Hello!

Can I control time for visibility? I want to add some pause after error, for example 2 minutes before it will be processed again.

![image](https://user-images.githubusercontent.com/30263513/160059563-05c98f64-b784-47a4-9e19-e9d1a21bda32.png)

**Comment by mookid8000** [comment]
Oh that's actually a pretty good idea!

I could imagine a configuration based on a callback, which would enable inspection of the received message etc when deciding the delay - something like this:
```csharp
services.AddRebus(
	configure => configure
		.Transport(t => {
			t.UseAmazonSQS(...)
				.ConfigureMessageVisibilityDelayOnAbort(context => TimeSpan.FromMinutes(2));	
		})
);
```

How do you think that looks?

**Comment by kostazol** [comment]
>How do you think that looks?

 It's great config api!
