### ISSUE TITLE
Receiving SQS Messages from Eventbridge

### ISSUE THREAD

**Issue by mccow002** [rebus-org/Rebus.AmazonSQS#43]
I'm having the same issue as the person who asked #41. I have an Eventbridge filter sending a native SQS message that I would like to receive with Rebus. 

My question is this - how do I access the raw message body of an SQS message in Rebus? Because the raw message isn't in the shape of the Rebus SQS message envelope, the Body property is always empty.

**Comment by mookid8000** [comment]
You can't do that.

Rebus wraps the message headers and message body in its own envelope format to overcome some limitations in SQS. This (+ some other things) contribute to Rebus have some pretty strict requirements as to how messages are formatted.

Generally, I do not recommend that Rebus is used to receive messages directly from other systems, as it's generally not very flexible in what it requires to be present. What I recommend instead, is that you treat this as a regular integration scenario and create a [channel adapter](https://www.enterpriseintegrationpatterns.com/patterns/messaging/ChannelAdapter.html) that takes messages out of your SQS queue and forwards them (using a Rebus one-way client) to a regular Rebus queue.

I hope that makes sense. 🙂
