### ISSUE TITLE
manually "receive" a message to the bus

### ISSUE THREAD

**Issue by stevenrobertscrew** [rebus-org/Rebus.AmazonSQS#46]
I use Rebus to send a message to an SQS queue from an Api.  I am then processing the message with a lambda with the signature of 
```
public async Task FunctionHandler(SQSEvent evt, ILambdaContext context)
```
Of course, the SQSEvent has many records, each being a queue message.  I know that the body of the message looks like a typical Rebus message.  What I want to do is get that message and "give" it to Rebus to handle.  The short answer I think is no, this doesn't even make sense but I thought I would ask and perhaps you have a different idea of how you'd handle this scenario.

**Comment by mookid8000** [comment]
> What I want to do is get that message and "give" it to Rebus to handle. The short answer I think is no, this doesn't even make sense but I thought I would ask and perhaps you have a different idea of how you'd handle this scenario.

Yeah, is you want Rebus to handle the message you need to let Rebus receive it.

My guess is that you just want to create a .NET background service and deploy in a Docker container somehow, but unfortunately I am not familiar enough with Amazon's cloud to tell you what their best option is.
