### ISSUE TITLE
Change casing in package references.

### ISSUE THREAD

**Issue by robvanpamel** [rebus-org/Rebus.AmazonSQS#7]
Hi,

Could you change line 51 in https://github.com/rebus-org/Rebus.AmazonSQS/blob/master/Rebus.AmazonSQS/Rebus.AmazonSQS.csproj to use the correct casing.
If you are using .NET Core with project.json files this causes an issue that **r**ebus cannot be found (since it should be **R**ebus)

Before:

    <ItemGroup>
        <PackageReference Include="awssdk.sqs" Version="3.3.1.10" />
        <PackageReference Include="rebus" Version="4.0.0-b05" />
    </ItemGroup>
After:

     <ItemGroup>
        <PackageReference Include="awssdk.sqs" Version="3.3.1.10" />
        <PackageReference Include="Rebus" Version="4.0.0-b05" />
    </ItemGroup>
Thanks

**Comment by mookid8000** [comment]
I think this was fixed by #8
